name: Python Gauge Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Gauge
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        curl -fsSL https://downloads.gauge.org/stable/gauge-repository.key | sudo gpg --dearmor -o /usr/share/keyrings/gauge-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/gauge-archive-keyring.gpg] https://downloads.gauge.org/stable nightly main" | sudo tee /etc/apt/sources.list.d/gauge.list
        sudo apt-get update
        sudo apt-get install -y gauge
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run Gauge tests
      run: gauge run specs/
      env:
        PYTHONPATH: ${{ github.workspace }}