name: Python Gauge Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Gauge from Binary
      run: |
        curl -L https://github.com/getgauge/gauge/releases/latest/download/gauge-linux-x86_64.tar.gz -o gauge.tar.gz
        sudo tar -xvzf gauge.tar.gz -C /usr/local/bin
        gauge --version    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run Gauge tests
      run: gauge run specs/
      env:
        PYTHONPATH: ${{ github.workspace }}